"""DataFrame filters used by the Streamlit app.

The app must reflect the dataset generated by the training repository.
For this project scope, the visible dataset is limited to animals and plants.
The taxonomic class selector is built dynamically from the current parquet,
not from a hardcoded list.
"""

from __future__ import annotations

import pandas as pd


PROJECT_SCOPE_KINGDOMS = {"Animalia", "Plantae"}
# Backward-compatible alias used by some older tests/patches.
PROJECT_KINGDOMS = PROJECT_SCOPE_KINGDOMS


def filter_project_scope(df: pd.DataFrame) -> pd.DataFrame:
    """Return only rows inside the project scope: Animalia + Plantae.

    This protects the UI if an old/full artifact still contains Fungi or other
    kingdoms. Unlike older versions, it does not silently fall back to the full
    dataframe when the scoped result is empty, because that would re-expose
    out-of-scope classes in the sidebar.
    """
    if df.empty or "kingdom" not in df.columns:
        return df.copy()

    normalized_kingdom = df["kingdom"].fillna("").astype(str).str.strip()
    return df.loc[normalized_kingdom.isin(PROJECT_SCOPE_KINGDOMS)].copy()


def get_available_taxon_classes(df: pd.DataFrame) -> list[str]:
    """Build available taxonomic classes dynamically from the current dataset.

    There is no hardcoded class list in the app. If the Hugging Face artifact
    changes, the sidebar filter changes with it.
    """
    scoped_df = filter_project_scope(df)

    if scoped_df.empty or "taxon_class" not in scoped_df.columns:
        return []

    classes = scoped_df["taxon_class"].dropna().astype(str).str.strip()
    classes = classes[classes.ne("")]

    return sorted(classes.unique().tolist())


def apply_basic_filters(
    df: pd.DataFrame,
    selected_classes: list[str] | None,
    min_observations: int,
) -> pd.DataFrame:
    """Apply sidebar filters with df.loc.

    Filtering order:
    1. Project scope: Animalia + Plantae.
    2. Minimum observations.
    3. Dynamic class filter.
    """
    filtered_df = filter_project_scope(df)

    if "observations" in filtered_df.columns:
        observations = pd.to_numeric(
            filtered_df["observations"],
            errors="coerce",
        ).fillna(0)
        filtered_df = filtered_df.loc[observations >= min_observations].copy()

    if selected_classes and "taxon_class" in filtered_df.columns:
        filtered_df = filtered_df.loc[
            filtered_df["taxon_class"].isin(selected_classes)
        ].copy()

    return filtered_df
